### ISSUE TITLE
报错了怎么处理??我是小米6.0系统

### ISSUE THREAD

**Issue by lxhtiamo** [zhouzhuo810/CameraCardCropDemo#2]
错误提示::java.lang.RuntimeException: Camera is being used after Camera.release() was called
                                                                            at android.hardware.Camera.native_cancelAutoFocus(Native Method)
                                                                            at android.hardware.Camera.cancelAutoFocus(Camera.java:1317)
                                                                            at com.linewell.smartcity.ui.cameracardcrop.AutoFocusManager.stop(AutoFocusManager.java:98)
                                                                            at com.linewell.smartcity.ui.cameracardcrop.CameraView.surfaceDestroyed(CameraView.java:119)

代码位置::/**
     * 停止自动对焦
     */
    public synchronized void stop() {
        stopped = true;
        if (useAutoFocus) {
            cancelOutstandingTask();
            // Doesn't hurt to call this even if not focusing
            try {
                camera.cancelAutoFocus();    这里报错
            } catch (RuntimeException re) {
                // Have heard RuntimeException reported in Android 4.0.x+; continue?
                Log.e(TAG, "Unexpected exception while cancelling focusing", re);
            }
        }
    }

**Comment by zhouzhuo810** [comment]
这种错误不影响使用呀 而且我try catch了
