### ISSUE TITLE
某些手机打开相机会报错  Fail to connect to camera service

### ISSUE THREAD

**Issue by xinshengBoy** [zhouzhuo810/CameraCardCropDemo#4]
java.lang.RuntimeException: Unable to resume activity {com.yks.scancollectgoods/me.zhouzhuo810.cameracardcrop.CropActivity}: java.lang.RuntimeException: Fail to connect to camera service
                                                                              at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3001)
                                                                              at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3030)
                                                                              at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2424)
                                                                              at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1342)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                              at android.os.Looper.loop(Looper.java:193)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:5339)
                                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                                              at java.lang.reflect.Method.invoke(Method.java:515)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:828)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:644)
                                                                              at dalvik.system.NativeStart.main(Native Method)
                                                                           Caused by: java.lang.RuntimeException: Fail to connect to camera service
                                                                              at android.hardware.Camera.native_setup(Native Method)
                                                                              at android.hardware.Camera.<init>(Camera.java:472)
                                                                              at android.hardware.Camera.open(Camera.java:427)
                                                                              at me.zhouzhuo810.cameracardcrop.CameraUtils.open(CameraUtils.java:66)
                                                                              at me.zhouzhuo810.cameracardcrop.CropActivity.resumeCamera(CropActivity.java:202)
                                                                              at me.zhouzhuo810.cameracardcrop.CropActivity.onResume(CropActivity.java:189)
                                                                              at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1197)

**Comment by zhouzhuo810** [comment]
什么手机？系统版本？CAMERA权限有没有通过？有没有手机管家限制相机权限？

**Comment by xinshengBoy** [comment]
跟我们平时用的手机不一样，我现在调试的是ZEBRA斑马手持PDA，就是带红外线扫描头的那种，然后用你写的这个控件打开摄像头的时候就失败了，但我用原生的方法打开摄像头又是正常的

**Comment by xinshengBoy** [comment]
版本是4.4.2，有权限，没有限制权限

**Comment by zhouzhuo810** [comment]
有后置摄像头么？

**Comment by zhouzhuo810** [comment]
我估计是你没加：
```
    <uses-permission android:name="android.permission.CAMERA" />
    <uses-feature android:name="android.hardware.camera" />
    <uses-feature android:name="android.hardware.camera.autofocus" />
```
